apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-weatherbroadcaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-weatherbroadcaster
  template:
    metadata:
      labels:
        app: ts-weatherbroadcaster
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: ts-weatherbroadcaster
          image: lsstts/ts-weatherbroadcaster:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: TS_WEATHERBROADCASTER_LOG_LEVEL
              value: INFO
          volumeMounts:
            - name: weather-data
              mountPath: /data
              readOnly: true
      volumes:
        - name: weather-data
          persistentVolumeClaim:
            claimName: ts-weatherbroadcaster-weather-data
