apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherbroadcaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherbroadcaster
  template:
    metadata:
      labels:
        app: weatherbroadcaster
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: weatherbroadcaster
          image: lsstts/weatherbroadcaster:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: WEATHERBROADCASTER_LOG_LEVEL
              value: INFO
          volumeMounts:
            - name: weather-data
              mountPath: /data
              readOnly: true
        - name: update-weather
          image: lsstts/weatherbroadcaster:latest
          imagePullPolicy: Always
          command:
            - weatherbroadcaster
            - update
            - --loop
          env:
            - name: WEATHERBROADCASTER_LOG_LEVEL
              value: INFO
            - name: WEATHERBROADCASTER_WEATHER_UPDATE_INTERVAL
              value: "3600"
          volumeMounts:
            - name: weather-data
              mountPath: /data
      volumes:
        - name: weather-data
          persistentVolumeClaim:
            claimName: weatherbroadcaster-weather-data
