[project]
title = "weatherbroadcaster"
copyright = "2026 Association of Universities for Research in Astronomy, Inc. (AURA)"

[project.python]
package = "weatherbroadcaster"

[project.openapi]
openapi_path = "_static/openapi.json"
doc_path = "api"

[project.openapi.generator]
function = "weatherbroadcaster.main:create_openapi"

[sphinx]
nitpicky = true
nitpick_ignore = [
    ["py:class", "fastapi.applications.FastAPI"],
    ["py:class", "structlog.stdlib.BoundLogger"],
    ["py:class", "pathlib.Path"],
]
